### ISSUE TITLE
Some questions about path settings.

### ISSUE THREAD

**Issue by KinberAlan** [GuHuangAI/DiffusionEdge#13]
Thank you very much for your sharing！
But I encountered some issues that have left me very confused while executing the code.So, I would like to seek your advice on these issues.
I have already made modifications to the paths in the "args" section of the code, but the code is still using the initial default paths when it runs. I cannot find any other information regarding path settings in the file. What could be the reason for this, and how can I modify the paths in the code to use my own paths?
![屏幕截图 2024-02-27 164343](https://github.com/GuHuangAI/DiffusionEdge/assets/97089303/9fbf1871-5201-4cf2-8f83-3a23d7fbef27)

**Comment by GuHuangAI** [comment]
What is the running command?

**Comment by KinberAlan** [comment]
I didn't run it using a command; instead, I modified the default path information in the "args" section and then run the demo.py.
I can use the command to run  it  without any issues, but I am unsure why the another running method is causing issues.I am unable to change its path.

**Comment by GuHuangAI** [comment]
I don't met this problem. Please check if you have saved the file before running.

**Comment by KinberAlan** [comment]
I have already solved this problem. Thank you very much for your kind help！
