### ISSUE TITLE
Using images with just 1 channel instead of RGB

### ISSUE THREAD

**Issue by f-hader** [GuHuangAI/DiffusionEdge#18]
Hi, I am interested in trying out your model for analyzing some measurement data that has only one channel. How can I customize your model and training code to work for single channel inputs? I don't think it's a good option to just store the same data on three channels...

**Comment by GuHuangAI** [comment]
Hello, you can use the modified backbone for single-channel image.
Please refer to the single channel Swin-transformer [https://github.com/GuHuangAI/DDM-Public/blob/main/unet/swin_transformer_for_sci.py](here).

**Comment by f-hader** [comment]
Thank you very much, I was able to modify the network and training code for 1D and will start training now.
