### ISSUE TITLE
Latent discretization

### ISSUE THREAD

**Issue by okada-masashi** [GuHuangAI/DiffusionEdge#39]
I am curious about the performance of discretizing latent representations.

I found the [VQVAE code](https://github.com/GuHuangAI/DiffusionEdge/blob/b03617e84b79336fd1f4d650105580e026ab26a7/taming/modules/vqvae/quantize.py#L9) in the GitHub repository and would like to ask if you have already tried the discretization?

**Comment by GuHuangAI** [comment]
Hello, I have not tried to utilize the discrete representation.

**Comment by okada-masashi** [comment]
Thank you for your response.
If you try it, I would appreciate it if you could share the results.
