### ISSUE TITLE
AttributeError和subprocess.CalledProcessError

### ISSUE THREAD

**Issue by isyzwang** [GuHuangAI/DiffusionEdge#6]
你好，我在运行accelerate launch train_cond_ldm.py --cfg ./configs/BSDS_train.yaml时遇到问题，可以给我提供一些帮助吗？
![image](https://github.com/GuHuangAI/DiffusionEdge/assets/130199146/bf56d2e2-6e48-4832-964d-a14d87a35ece)

**Comment by GuHuangAI** [comment]
@isyzwang  请问你配置accelerate config了吗？

**Comment by GuHuangAI** [comment]
@isyzwang 你可以尝试将该语句中的 model 替换为 accelerator

**Comment by GuHuangAI** [comment]
Please provide the running command.

**Comment by isyzwang** [comment]
我在执行python sample_cond_ldm.py --cfg ./configs/BSDS_sample.yaml时出现上述问题

**Comment by GuHuangAI** [comment]
@isyzwang
If you want to train from scratch, you have better set the line 76 of `./configs/BSDS_train.yaml` to `True`. (Please see line 222 of `train_cond_ldm.py`.)
Otherwise, the default training do not save the ema weight. In this case, you can set `use_ema` (line 71) of `./configs/BSDS_sample.yaml` to `False` to run sampling.

**Comment by isyzwang** [comment]
谢谢您的解答，我已经成功训练自己的数据集，就是还有一个小问题，就是在利用你们的权重文件去测试图片时报错，也就是在运行demo文件时报错
![image](https://github.com/GuHuangAI/DiffusionEdge/assets/130199146/91499f16-047d-40d0-965a-ba33de1a70ce)

**Comment by GuHuangAI** [comment]
@isyzwang 
What's the size of your testing image? The size of testing image must be larger than 320x320 when using the provided weights.

**Comment by isyzwang** [comment]
和你们数据集的大小是一样的481x321

**Comment by GuHuangAI** [comment]
Ok, could you provide the testing image? I'll check if there is a bug.

**Comment by isyzwang** [comment]
找到错误了，测试集中不小心混入了一张456x304的图片，导致这一张及以后的图片没有测试成功，谢谢您的回复
